'use strict';
const assert=require('node:assert/strict');
const pack=require('./badge-wow-inspired-copyworking.json');
const story=require('./badge-60-story-20-history-working.json');
const registry=require('./badge-visual-registry-working.json');
const {validateNamingPack}=require('./badge-wow-inspired-copy-validator.js');
const valid=validateNamingPack(pack,story);
assert.equal(valid.ok,true,JSON.stringify(valid.issues));
assert.deepEqual([valid.preset,valid.history],[60,20]);
assert.equal(registry.items.every(x=>x.active===false&&x.asset_state==='UNBOUND'&&x.renderer_binding===false),true);
assert.equal(pack.preset_copy[0].canonical_title,story.presets[0].stable_name);
assert.equal(pack.discovery_copy[0].canonical_title,story.history_discovery_templates[0].suggested_title);
assert.equal(pack.preset_copy.every(x=>x.changes_criteria===false&&x.changes_ownership===false&&x.display_status==='COPY_PROPOSAL_NOT_RUNTIME_APPROVED'),true);
const names=[...pack.preset_copy,...pack.discovery_copy].map(x=>x.display_title_proposal);
assert.equal(new Set(names).size,80);
const mutated=structuredClone(pack);
mutated.preset_copy[0].canonical_title='REPLACED SOURCE';
assert.equal(validateNamingPack(mutated,story).ok,false);
const active=structuredClone(pack);
active.discovery_copy[0].display_status='APPROVED';
assert.equal(validateNamingPack(active,story).ok,false);
const awarding=structuredClone(pack);
awarding.preset_copy[1].changes_ownership=true;
assert.equal(validateNamingPack(awarding,story).ok,false);
const duplicate=structuredClone(pack);
duplicate.discovery_copy[0].display_title_proposal=duplicate.preset_copy[0].display_title_proposal;
assert.equal(validateNamingPack(duplicate,story).ok,false);
console.log('WOW_INSPIRED_ORIGINAL_BADGE_COPY_PASS: 60 + 20, canonical stable, unique original Korean titles, no award/art activation');
