'use strict';
const assert=require('node:assert/strict');
const W=require('./world-state.js');
let w=W.empty('C1');
let r=W.apply(w,{event_id:'E1',type:'SET_MAIN_COMPANION',character_id:'crew.core.dubi',occurred_at:'2026-09-26T00:00:00Z'});
assert.equal(r.ok,true);w=r.world;assert.equal(w.crew['crew.core.dubi'].state,'MAIN_COMPANION');
r=W.apply(w,{event_id:'E2',type:'SET_MAIN_COMPANION',character_id:'crew.core.ink'});
assert.equal(r.world.crew['crew.core.dubi'].state,'AT_HUB');assert.equal(r.world.crew['crew.core.ink'].state,'MAIN_COMPANION');
const dup=W.apply(r.world,{event_id:'E2',type:'SET_MAIN_COMPANION',character_id:'crew.core.ink'});assert.equal(dup.reason,'IDEMPOTENT_ALREADY_APPLIED');
const bad=W.apply(r.world,{event_id:'E3',type:'CREW_STATE_SET',character_id:'crew.core.nova',state:'POWERED_UP'});assert.equal(bad.ok,false);
assert.equal(W.canonicalFromSynthetic({state:'VACATION'}).ok,false);
assert.equal(r.world.absence_penalty,false);assert.equal(r.world.full_daily_simulation,false);
console.log('TAKY_WORLD_STATE_V1_PASS');